name: "lods-gs"
tag: "${rmspace:${system.prompt_processor.prompt},_}"
exp_root_dir: "outputs"
seed: 0
 
data_type: "random-camera-datamodule-gs"
data:
  batch_size: 8
  eval_camera_distance: 4.0
  camera_distance_range: [2.5, 4.0]
  light_sample_strategy: "dreamfusion3dgs"
  height: 512
  width: 512
  eval_height: 512
  eval_width: 512
  fovy_range: [40, 70]
  elevation_range: [-10, 45]
system_type: "lods-gs-system"
system:
  radius: ${data.eval_camera_distance}
  prompt_processor_type: "stable-diffusion-prompt-processor"
  prompt_processor:
    pretrained_model_name_or_path: "stabilityai/stable-diffusion-2-1-base"
    prompt: ???
    negative_prompt: "a point cloud image"

  guidance_type: "lods-embedding-guidance"
  guidance:
    pretrained_model_name_or_path: "stabilityai/stable-diffusion-2-1-base"
    guidance_scale: 1000.
    min_step_percent: 0.02
    max_step_percent: [1000, 0.98, 0.5, 1001]

  loggers:
    wandb:
      enable: false
      project: 'threestudio'
      name: None

  loss:
    lambda_sds: 1.
    lambda_embedding: 1.
    lambda_sparsity: 1.
    lambda_opaque: 0.0
  optimizer:
    name: AdamW
    args:
      lr: 0.001
      betas: [0.9, 0.99]
      eps: 1.e-15
    params:
      guidance.learnable_embedding:
        lr: 0.00001

trainer:
  max_steps: 2500
  log_every_n_steps: 1
  num_sanity_val_steps: 0
  val_check_interval: 100
  enable_progress_bar: true
  precision: 16-mixed

checkpoint:
  save_last: true # save at each validation time
  save_top_k: -1
  every_n_train_steps: ${trainer.max_steps}

# white_background: true